# Use postgres/example user/password credentials
networks:
  proj_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 177.10.10.0/24

services:
    db:
       image: "postgres:latest"
       container_name: postgres_go
       expose:
         - "5436"
       ports:
         - "5436:5432"
       restart: always    
       working_dir: /code  
       environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres    
       restart: unless-stopped
       volumes: 
           - ./postgres-data:/var/lib/postgresql/data
           - ./scripts:/scripts
             # copy the sql script to create tables
           - ./init.sql:/docker-entrypoint-initdb.d/init.sql
       #mac_address: 02:42:c0:a8:84:22
       networks:
          proj_net:
            ipv4_address: 177.10.10.10
    app:
       container_name: challenges
       build: .
       working_dir: /code/app
       command: uvicorn main:app --host 0.0.0.0 --reload
       environment:
          DEBUG: 1
       volumes:
        - ./filesGo:/filesGo
        - ./challenges:/code/app
       ports:
        - 8008:8000
       restart: on-failure
       depends_on:
          - db
       links:
          - db
       networks:
          proj_net:
            ipv4_address: 177.10.10.20
    

